apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubuntu-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ubuntu.local.org
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: ubuntu
            port:
              number: 8080