apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-broker-pv0
    labels:
      type: kafka-broker-pv
  spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-761/broker-0
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-broker-pv1
    labels:
      type: kafka-broker-pv
  spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-761/broker-1
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-broker-pv2
    labels:
      type: kafka-broker-pv
  spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-761/broker-2
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-controller-pv0
    labels:
      type: kafka-controller-pv
  spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-761/controller-0
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-controller-pv1
    labels:
      type: kafka-controller-pv
  spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-761/controller-1
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-controller-pv2
    labels:
      type: kafka-controller-pv
  spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-761/controller-2
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-connect-pv
    labels:
      type: kafka-connect-pv
  spec:
    capacity:
      storage: 3Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-761/connect
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: kafka-connect-pvc
  spec:
    storageClassName: local-storage
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi