apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-pv0
    labels:
      type: kafka-pv
  spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-new-0
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-pv1
    labels:
      type: kafka-pv
  spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-new-1
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-pv2
    labels:
      type: kafka-pv
  spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
      path: /data/kafka-new-2
    nodeAffinity:
      required:
       nodeSelectorTerms:
         - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
               - primary