apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-broker.headlessServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
spec:
  ports:
  {{- range .Values.headless}}
    - port: {{ .port }}
      name: {{ .name }}
  {{- end}}
  clusterIP: None
  selector:
    {{- include "kafka-broker.selectorLabels" . | nindent 4}}
