---
# Source: kafka-broker/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-broker.serviceAccountName" .}}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
