apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms-cp-kafka.headlessServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ms-cp-kafka.labels" . | nindent 4 }}
spec:
  ports:
      {{- range .Values.headless}}
    - port: {{ .port }}
      name: {{ .name }}
      {{- end}}
  clusterIP: None
  selector:
    {{- include "ms-cp-kafka.selectorLabels" . | nindent 4}}
