apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "kafka-ui.selectorLabels" . | nindent 4 }}
