apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-controller.configMapName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kafka-controller.labels" . | nindent 4 }}  
data:
{{- range $key, $value := .Values.environment}}
    {{ $key }}: "{{ $value }}"
{{- end }}