apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-controller.headlessServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kafka-controller.labels" . | nindent 4 }}
spec:
  ports:
  {{- range .Values.headless}}
    {{- if eq .name "kafka-controller" }}
    - port: {{ .port }}
      name: {{ .name }}
    {{- end}}
  {{- end}}
  clusterIP: None
  selector:
    {{- include "kafka-controller.selectorLabels" . | nindent 4}}
