---
# Source: kafka-controller/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-controller.serviceName" .}}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kafka-controller.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "kafka-controller.selectorLabels" . | nindent 4}}
