---
# Source: kafka-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-controller.serviceAccountName" .}}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kafka-controller.labels" . | nindent 4 }}
